export const OrchidData = [
    {
        id: 1,
        category: 'Dendrobium',
        productName: 'Dendrobium lindleyi',
        description: 'Dendrobium lindleyi is a species of orchid. It is native to the Himalayas, China, India, Nepal, Bhutan, Assam, Laos, Myanmar, Thailand, and Vietnam.',
        orchidImage: require('../database/OrchidsImages/Dendrobium_lindleyi.jpg'),
    },
    {
        id: 2,
        category: 'Dendrobium',
        productName: 'Dendrobium nobile',
        description: 'Dendrobium nobile is a member of the family Orchidaceae. It is native to southern China, the Himalayas, and Indochina.',
        orchidImage: require('../database/OrchidsImages/Dendrobium_nobile.jpg'),
    },
    {
        id: 3,
        category: 'Dendrobium',
        productName: 'Dendrobium anosmum',
        description: 'Dendrobium anosmum is a species of orchid. It is native to the Himalayas, China, India, Nepal, Bhutan, Assam, Laos, Myanmar, Thailand, and Vietnam.',
        orchidImage: require('../database/OrchidsImages/Dendrobium_anosmum.jpg'),
    },
    {
        id: 4,
        category: 'Cattleya',
        productName: 'Cattleya trianae',
        description: 'Cattleya trianae is a species of orchid. It is native to Colombia.',
        orchidImage: require('../database/OrchidsImages/Cattleya_trianae.jpg'),
    },
    {
        id: 5,
        category: 'Cattleya',
        productName: 'Cattleya labiata',
        description: 'Cattleya labiata is a species of orchid. It is native to Brazil.',
        orchidImage: require('../database/OrchidsImages/Cattleya_labiata.jpg'),
    },
    {
        id: 6,
        category: 'Cattleya',
        productName: 'Cattleya tainan',
        description: 'Cattleya tainan is a species of orchid. It is native to Taiwan.',
        orchidImage: require('../database/OrchidsImages/Cattleya_tainan.jpg'),
    },
    {
        id: 7,
        category: 'Phalaenopsis',
        productName: 'Phalaenopsis amabilis',
        description: 'Phalaenopsis amabilis is a species of orchid. It is native to the Philippines.',
        orchidImage: require('../database/OrchidsImages/Phalaenopsis_amabilis.jpg'),
    },
    {
        id: 8,
        category: 'Phalaenopsis',
        productName: 'Phalaenopsis aphrodite',
        description: 'Phalaenopsis aphrodite is a species of orchid. It is native to Taiwan.',
        orchidImage: require('../database/OrchidsImages/Phalaenopsis_aphrodite.jpg'),
    },
    {
        id: 9,
        category: 'Phalaenopsis',
        productName: 'Phalaenopsis bellina',
        description: 'Phalaenopsis bellina is a species of orchid. It is native to Borneo.',
        orchidImage: require('../database/OrchidsImages/Phalaenopsis_bellina.jpg'),
    },
]